import burger from './modules/burger';
import calculator from './modules/calculator';
import callBackForm from './modules/callBackForm';
import carousel from './modules/carousel';
import clubSelect from './modules/clubSelect';
import freeVisitForm from './modules/freeVisitForm';
import gift from './modules/gift';
import photoGallery from './modules/photoGallery';
import slider from './modules/slider';
import toTop from './modules/toTop';
import forms from './modules/forms';
import otherThings from './modules/valid';

clubSelect();
freeVisitForm();
callBackForm();
gift();
slider();
carousel();
photoGallery();
calculator();
burger();
toTop();
otherThings();
forms('form1', 'none');
forms('form2', 'none');
forms('banner-form');
forms('card_order');
forms('footer_form');
